### ISSUE TITLE
Bad request error (password is missing) after linking an account

### ISSUE THREAD

**Issue by blackhexagon** [anatosun/plex2mix#11]
Hello,

after entering a code to https://www.plex.tv/link/ the page displays "Your account has been successfully linked, please revisit your app to continue.", but  I get the following error from the command line:

```
Please visit https://plex.tv/link and enter the following code: ****
Waiting for authorization...
Traceback (most recent call last):
  File "C:\Users\matou\AppData\Roaming\Python\Python311\Scripts\plex2mix-script.py", line 33, in <module>
    sys.exit(load_entry_point('plex2mix==0.1.0', 'console_scripts', 'plex2mix')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matou\AppData\Roaming\Python\Python311\site-packages\click-8.1.7-py3.11.egg\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matou\AppData\Roaming\Python\Python311\site-packages\click-8.1.7-py3.11.egg\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\matou\AppData\Roaming\Python\Python311\site-packages\click-8.1.7-py3.11.egg\click\core.py", line 1685, in invoke
    super().invoke(ctx)
  File "C:\Users\matou\AppData\Roaming\Python\Python311\site-packages\click-8.1.7-py3.11.egg\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matou\AppData\Roaming\Python\Python311\site-packages\click-8.1.7-py3.11.egg\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matou\AppData\Roaming\Python\Python311\site-packages\click-8.1.7-py3.11.egg\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matou\AppData\Roaming\Python\Python311\site-packages\plex2mix-0.1.0-py3.11.egg\plex2mix\main.py", line 32, in cli
  File "C:\Users\matou\AppData\Roaming\Python\Python311\site-packages\plex2mix-0.1.0-py3.11.egg\plex2mix\main.py", line 91, in login
  File "C:\Users\matou\AppData\Roaming\Python\Python311\site-packages\plexapi-4.15.1-py3.11.egg\plexapi\myplex.py", line 123, in __init__
    data, initpath = self._signin(username, password, code, remember, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matou\AppData\Roaming\Python\Python311\site-packages\plexapi-4.15.1-py3.11.egg\plexapi\myplex.py", line 136, in _signin
    data = self.query(self.SIGNIN, method=self._session.post, data=payload, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matou\AppData\Roaming\Python\Python311\site-packages\plexapi-4.15.1-py3.11.egg\plexapi\myplex.py", line 242, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (400) bad_request; https://plex.tv/api/v2/users/signin <?xml version="1.0" encoding="UTF-8"?> <errors>   <error code="1004" message="password is missing" status="400"/> </errors>
```

Any ideas? Thank you

**Comment by marclight** [comment]
Same for me on Fedora 39.

**Comment by sonnd9x** [comment]
same issue on Ubuntu 22.04

**Comment by bencorryp** [comment]
Anyone find a solution for this? On Windows 11 Powershell 7 and getting the same error. Potentially that plex is blocking password retrieval?

**Comment by bencorryp** [comment]
Have tried this on ubuntu via WSL now also, still encountering the same error.

**Comment by christiankopac** [comment]
Run into the same on Fedora... Didn't look into why the config file is not getting the data save after linking.

In any case, as a workaround, here is how the configuration file should look like (found in `~/config/plex2mix/config.yaml`)
```yaml
token: <plex_token>
server:
  url: <plex_server_url>
  name: <plex_server_name>
path: <download_path>
threads: <number_of_threads>
playlists:
  saved: 
    - <playlist_id_1>
    - <playlist_id_2>
    # ... more saved playlist IDs
  ignored: 
    - <playlist_id_3>
    - <playlist_id_4>
    # ... more ignored playlist IDs
playlists_path: <path_to_playlists_directory>
```
You can get the Plex Token with [curl](https://gist.github.com/alghanmi/346ecef6261d772b52b04efd5ff5cb77) or inspecting the network panel in your browser.

With the min. required:
```yaml
token: "MyPlexToken"
server:
  url: "http://192.168.1.1:32400"
  name: "MyPlexServerName"
path: /home/MyUser/music/plex2mix
threads: 4
```

Save the file and run `plex2mix list`, it should now show you your playlists.

**Comment by bencorryp** [comment]
Thanks a bunch @christiankopac! Works like a charm.

(p.s. for people who can't use linux (like me), the path to config is ~/.config/plex2mix)

**Comment by agneyakerure** [comment]
Hi! Can someone please help me on how to find the config file on MacOS? 
I downloaded the zip file and installed it. I do not see the config.yaml file anywhere on my Mac.

**Comment by niklasbeinghaus** [comment]
> Hi! Can someone please help me on how to find the config file on MacOS? I downloaded the zip file and installed it. I do not see the config.yaml file anywhere on my Mac.

The software uses a library called ["click"](https://click.palletsprojects.com/en/7.x/api/#click.get_app_dir) which helps to make cli's work across multiple oses. For macOS, use `~/Library/Application Support/plex2mix/config.yaml` accordingly.

**Comment by anatosun** [comment]
There was a problem writing the token to the file as others have suggested. This might be due to permission issues.

Plex2mix can now be ran in verbose mode to show additional information, this could help knowing what the issue was: e.g., `plex2mix --verbose list`

**Comment by anatosun** [comment]
I'm closing this for now, feel free to reopen if the issue persists.
